# Site Specific Configuration
title: The Community Trash
description: A website for a fae üßöüèª‚Äç‚ôÇÔ∏è
url: https://adorablecyb.org
author: Missy
timezone: America/Los_Angeles
timezone_short: Pacific
remote_theme: tajacks/lightspeed
markdown: kramdown

# Keywords
# keywords: ['seo', 'key', 'words']

# Styling
sass:
  sass_dir: _sass
  style: expanded # compact, expanded or compressed

# Paginate
pagination:
  enabled: true
  permalink: '/:num/'
  per_page: 7
  sort_field: 'date'
  sort_reverse: true

# Category Paginating
autopages:
  enabled: true
  categories:
    title: 'Posts in category :cat'
    silent: false

# Exclusions
exclude: [ 'README.md', 'CNAME', '.gitignore' ]

# Plugins
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate-v2
